/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage.Transportation;

import MainPackage.MainWindow;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.border.TitledBorder;

/**
 *
 * @author ranjith
 */
public class TransportationMainFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 9220036263068464736L;
    int col_value,row_value;
    static TransportationMainFrame TransportWindow;
   
    /**
     * Creates new form TransportationMainFrame
     */
    public TransportationMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        row = new javax.swing.JTextField();
        col = new javax.swing.JTextField();
        ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRANSPORTATION PROBLEM");
        setResizable(false);

        jPanel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Input Window",TitledBorder.CENTER,TitledBorder.CENTER));

        jLabel1.setText("Enter number of Factory (rows)");

        jLabel2.setText("Enter number of WareHouse (columns)");

        row.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rowKeyTyped(evt);
            }
        });

        col.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                colKeyTyped(evt);
            }
        });

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        ok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                okKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(row, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(col)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(ok)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(row, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(col, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        try
        {
            row_value = Integer.parseInt(row.getText());
            col_value = Integer.parseInt(col.getText());
            if(row_value==0 && col_value==0)
            {
                row.setText("");
                col.setText("");
                row.requestFocusInWindow();
                JOptionPane.showMessageDialog(null,"Give input more than 0","ERROR",WARNING_MESSAGE);
            }
            else if(row_value == 0)
            {
                row.setText("");
                row.requestFocusInWindow();
                JOptionPane.showMessageDialog(null,"Give input more than 0","ERROR",WARNING_MESSAGE);
            }
            else if(col_value == 0)
            {
                col.setText("");
                col.requestFocusInWindow();
                JOptionPane.showMessageDialog(null,"Give input more than 0","ERROR",WARNING_MESSAGE);
            }
            else
            {
                TransportWindow.dispose();
                new  TransportationInput(400+75*col_value,400+40*row_value,row_value,col_value);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Invalid Input","ERROR",WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_okActionPerformed

    private void okKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_okKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            try
            {
                row_value = Integer.parseInt(row.getText());
                col_value = Integer.parseInt(col.getText());
                
                if(row_value==0 && col_value==0)
                {
                    row.setText("");
                    col.setText("");
                    row.requestFocusInWindow();
                    JOptionPane.showMessageDialog(null,"Give input more than 0","ERROR",WARNING_MESSAGE);
                }
                else if(row_value == 0)
                {
                    row.setText("");
                    row.requestFocusInWindow();
                    JOptionPane.showMessageDialog(null,"Give input more than 0","ERROR",WARNING_MESSAGE);
                }
                else if(col_value == 0)
                {
                    col.setText("");
                    col.requestFocusInWindow();
                    JOptionPane.showMessageDialog(null,"Give input more than 0","ERROR",WARNING_MESSAGE);
                }
                else
                {
                    TransportWindow.dispose();
                    new  TransportationInput(400+75*col_value,400+40*row_value,row_value,col_value);
                }
            }
            catch(Exception e)
            {               
                JOptionPane.showMessageDialog(null,"Invalid Input","ERROR",WARNING_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_okKeyPressed

    private void rowKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rowKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if((row.getText().length() >= 2) || ((character < '0') || (character >'9') && (character != '\b')))
        {
            evt.consume();  
        }
    }//GEN-LAST:event_rowKeyTyped

    private void colKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_colKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if((col.getText().length() >= 2) || ((character < '0') || (character >'9') && (character != '\b')))
        {
            evt.consume();  
        }
    }//GEN-LAST:event_colKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransportationMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransportationMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransportationMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransportationMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TransportWindow = new TransportationMainFrame();
                TransportWindow.setVisible(true);
                TransportWindow.setLocationRelativeTo(null);
                ImageIcon ico_img=new ImageIcon(MainWindow.class.getResource("bot.png"));
        try
        {
            TransportWindow.setIconImage(ico_img.getImage());
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField col;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ok;
    private javax.swing.JTextField row;
    // End of variables declaration//GEN-END:variables
}
