package MainPackage.Game_Dominance;

import MainPackage.MainWindow;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.border.TitledBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ranjith
 */
public class DominanceMainFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 9220036263068464736L;
    int col_value,row_value;
    static DominanceMainFrame DominanceWindow;
    /**
     * Creates new form DominanceMainFrame
     */
    public DominanceMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        row = new javax.swing.JTextField();
        col = new javax.swing.JTextField();
        ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DOMINANCE RULE");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Input Window",TitledBorder.CENTER,TitledBorder.CENTER));

        jLabel1.setText("Enter the number of Player A's strategy :");

        jLabel2.setText("Enter the number of Player B's strategy :");

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        ok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                okKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(row, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(col)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(ok)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(row, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(col, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        try
            {
                row_value = Integer.parseInt(row.getText());
                col_value = Integer.parseInt(col.getText());
                

                if(row_value==0 && col_value==0)
                {
                    row.setText("");
                    col.setText("");
                    row.requestFocusInWindow();
                    JOptionPane.showMessageDialog(null,"Give input more than 0","ERROR",WARNING_MESSAGE);
                }
                else if(row_value == 0)
                {
                    row.setText("");
                    row.requestFocusInWindow();
                    JOptionPane.showMessageDialog(null,"Give input more than 0","ERROR",WARNING_MESSAGE);
                }
                else if(col_value == 0)
                {
                    col.setText("");
                    col.requestFocusInWindow();
                    JOptionPane.showMessageDialog(null,"Give input more than 0","ERROR",WARNING_MESSAGE);
                }
                else
                {
                    
                    new Thread(new Runnable()
                            {
                                @Override
                                public void run()
                                {
                                    if(col_value != 2 && col_value != 1)
                                        new  DominanceInput(200+75*col_value,200+40*row_value,row_value,col_value);
                                    else if(col_value == 2)
                                        new  DominanceInput(200+120*col_value,200+40*row_value,row_value,col_value);
                                    else
                                        new  DominanceInput(200+200*col_value,200+40*row_value,row_value,col_value);
                                }
                            }).start();
                    DominanceWindow.dispose();
                }
            }
            catch(Exception e)
            {               
                JOptionPane.showMessageDialog(null,"Invalid Input","ERROR",WARNING_MESSAGE);
            }
    }//GEN-LAST:event_okActionPerformed

    private void okKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_okKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            try
            {
                row_value = Integer.parseInt(row.getText());
                col_value = Integer.parseInt(col.getText());
                

                if(row_value==0 && col_value==0)
                {
                    row.setText("");
                    col.setText("");
                    row.requestFocusInWindow();
                    JOptionPane.showMessageDialog(null,"Give input more than 0","ERROR",WARNING_MESSAGE);
                }
                else if(row_value == 0)
                {
                    row.setText("");
                    row.requestFocusInWindow();
                    JOptionPane.showMessageDialog(null,"Give input more than 0","ERROR",WARNING_MESSAGE);
                }
                else if(col_value == 0)
                {
                    col.setText("");
                    col.requestFocusInWindow();
                    JOptionPane.showMessageDialog(null,"Give input more than 0","ERROR",WARNING_MESSAGE);
                }
                else
                {
                    new Thread(new Runnable()
                            {
                                @Override
                                public void run()
                                {
                                    if(col_value != 2 && col_value != 1)
                                        new  DominanceInput(200+75*col_value,200+40*row_value,row_value,col_value);
                                    else if(col_value == 2)
                                        new  DominanceInput(200+120*col_value,200+40*row_value,row_value,col_value);
                                    else
                                        new  DominanceInput(200+200*col_value,200+40*row_value,row_value,col_value);
                                }
                            }).start();
                    DominanceWindow.dispose();
              
                }
            }
            catch(Exception e)
            {               
                JOptionPane.showMessageDialog(null,"Invalid Input","ERROR",WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_okKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DominanceMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DominanceMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DominanceMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DominanceMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DominanceWindow = new DominanceMainFrame();
                DominanceWindow.setLocationRelativeTo(null);
                DominanceWindow.setVisible(true);
                ImageIcon ico_img=new ImageIcon(MainWindow.class.getResource("bot.png"));
        try
        {
        DominanceWindow.setIconImage(ico_img.getImage());
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField col;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ok;
    private javax.swing.JTextField row;
    // End of variables declaration//GEN-END:variables
}
